# Generated by Django 2.0.2 on 2019-04-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_dayapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
