# Generated by Django 2.0.2 on 2019-04-19 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lucky_dayapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_dayapp', '0002_user_provider_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_media', models.FileField(blank=True, upload_to=lucky_dayapp.models.get_upload_path_offer)),
                ('top_up_coin', models.IntegerField(null=True)),
                ('cash', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime')),
                ('order_no', models.IntegerField(null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_media', models.FileField(blank=True, upload_to=lucky_dayapp.models.get_upload_path_profile)),
                ('coin', models.IntegerField(null=True)),
                ('cash', models.IntegerField(null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='ScratchCard',
            fields=[
                ('scratch_card_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_id', models.ForeignKey(db_column='offer_id', on_delete=django.db.models.deletion.CASCADE, to='lucky_dayapp.Offer')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scratch_card',
            },
        ),
        migrations.CreateModel(
            name='WireTransfer',
            fields=[
                ('wire_transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_no', models.CharField(max_length=18)),
                ('ifsc', models.CharField(max_length=18, null=True)),
                ('swift', models.CharField(max_length=18, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wire_transfer',
            },
        ),
    ]
