# Generated by Django 2.0.2 on 2019-04-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_dayapp', '0003_offer_order_profile_scratchcard_wiretransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='cash',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='top_up_coin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
