# Generated by Django 2.0.2 on 2019-04-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_dayapp', '0004_auto_20190419_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cash',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='coin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
