# Generated by Django 2.0.2 on 2019-04-20 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_dayapp', '0006_remove_order_order_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('leaderboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank_no', models.IntegerField(max_length=18)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
            ],
            options={
                'db_table': 'leaderboard',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='provider_id',
            field=models.CharField(blank=True, default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
