# Generated by Django 2.0.2 on 2019-04-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_dayapp', '0007_auto_20190420_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='rank_no',
            field=models.IntegerField(),
        ),
    ]
