# Generated by Django 2.0.2 on 2019-04-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_dayapp', '0009_auto_20190420_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_Settings',
            fields=[
                ('app_settings_id', models.AutoField(primary_key=True, serialize=False)),
                ('top_up_coin', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
    ]
