# Generated by Django 2.0.2 on 2019-04-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_dayapp', '0010_app_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_settings',
            name='top_up_coin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
