# Generated by Django 2.0.2 on 2019-06-11 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_dayapp', '0011_auto_20190426_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('paypal_primary_keys', models.AutoField(primary_key=True, serialize=False)),
                ('paypal_id', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paypal',
            },
        ),
    ]
