# Generated by Django 2.0.2 on 2019-06-11 15:20

from django.db import migrations, models
import lucky_dayapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_dayapp', '0012_paypal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemOffer',
            fields=[
                ('redeem_offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('redeem_offer_media', models.FileField(blank=True, upload_to=lucky_dayapp.models.get_upload_path_redeem_offer)),
                ('title', models.CharField(max_length=500)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('feature', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=10000)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'redeem_offer',
            },
        ),
    ]
