# Generated by Django 2.0.2 on 2019-06-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_dayapp', '0013_redeemoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
