# Generated by Django 2.0.2 on 2019-06-12 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_dayapp', '0014_paypal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to=settings.AUTH_USER_MODEL),
        ),
    ]
